/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get OAuth2 access token
         * @description Get access token using username and password.
         */
        post: operations["login_for_access_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login and get access + refresh tokens.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout and clear refresh token cookie.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Refresh Token
         * @description Refresh access token using refresh token.
         */
        get: operations["refresh_token"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint to verify the service is running.
         *     Returns a simple message indicating the service is healthy.
         */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hospitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hospital List
         * @description Get paginated list of hospital.
         */
        get: operations["get_hospital_list"];
        put?: never;
        /**
         * Create Hospital
         * @description Create a new hospital.
         */
        post: operations["create_hospital"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hospitals/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Hospitals By Service
         * @description Search hospitals providing a specific service.
         */
        get: operations["search_hospitals_by_service"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hospitals/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hospital
         * @description Get hospital by ID.
         */
        get: operations["get_hospital"];
        put?: never;
        post?: never;
        /**
         * Delete Hospital
         * @description Delete hospital by ID.
         */
        delete: operations["delete_hospital"];
        options?: never;
        head?: never;
        /**
         * Update Hospital
         * @description Update hospital by ID.
         */
        patch: operations["update_hospital"];
        trace?: never;
    };
    "/v1/pets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pet List
         * @description Get paginated list of pet.
         */
        get: operations["get_pet_list"];
        put?: never;
        /**
         * Create Pet
         * @description Create a new pet.
         */
        post: operations["create_pet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pets/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pet
         * @description Get pet by ID.
         */
        get: operations["get_pet"];
        put?: never;
        post?: never;
        /**
         * Delete Pet
         * @description Delete pet by ID.
         */
        delete: operations["delete_pet"];
        options?: never;
        head?: never;
        /**
         * Update Pet
         * @description Update pet by ID.
         */
        patch: operations["update_pet"];
        trace?: never;
    };
    "/v1/pets/{entity_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pet Image
         * @description Get pet image.
         */
        get: operations["get_pet_image"];
        put?: never;
        /**
         * Upload Pet Image
         * @description Upload pet image.
         */
        post: operations["upload_pet_image"];
        /**
         * Delete Pet Image
         * @description Delete pet image.
         */
        delete: operations["delete_pet_image"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Users
         * @description Get paginated list of users with optional filters.
         */
        get: operations["get_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description Register a new user.
         */
        post: operations["register_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Profile
         * @description Get current authenticated user's profile.
         */
        get: operations["get_current_user_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User
         * @description Get user by ID.
         */
        get: operations["get_user"];
        put?: never;
        post?: never;
        /**
         * Delete User
         * @description Delete user by ID.
         */
        delete: operations["delete_user"];
        options?: never;
        head?: never;
        /**
         * Update User
         * @description Update user by ID.
         */
        patch: operations["update_user"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_for_access_token_v1_auth_token_post */
        Body_login_for_access_token_v1_auth_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Body_upload_pet_image_v1_pets__entity_id__image_post */
        Body_upload_pet_image_v1_pets__entity_id__image_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * CreateHospital
         * @description Schema for creating a new hospital
         */
        CreateHospital: {
            /**
             * Name
             * @description Name of the hospital
             */
            name: string;
            /**
             * Address
             * @description Address of the veterinary hospital
             */
            address: string;
            /**
             * Phone Number
             * @description Contact phone number
             */
            phone_number: string;
            /**
             * Services
             * @description List of services offered
             */
            services?: string[];
            /**
             * Capacity
             * @description Maximum number of pet patients the hospital can admit
             * @default 0
             */
            capacity: number;
        };
        /**
         * CreatePet
         * @description Schema for creating a new pet
         */
        CreatePet: {
            /**
             * Name
             * @description Name of the pet
             */
            name: string;
            /**
             * Description
             * @description Description of the pet
             */
            description?: string | null;
            /** @description ID of the owner (User) of the pet */
            owner_id: components["schemas"]["PydanticObjectId"];
        };
        /** CreateUser */
        CreateUser: {
            /**
             * Username
             * @description Username of the user
             */
            username: string;
            /**
             * Name
             * @description Name of the user
             */
            name: string;
            /**
             * Email
             * @description Email address of the user
             * @example user@email.com
             */
            email?: string | null;
            /**
             * Password
             * @description User password
             */
            password: string;
            /**
             * Confirm Password
             * @description Confirm user password
             */
            confirm_password: string;
            /**
             * Role
             * @description Role assigned to the user
             * @default user
             */
            role: string;
        };
        /** GetAccessTokenResponse */
        GetAccessTokenResponse: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Errors */
            errors?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheckResponse */
        HealthCheckResponse: {
            /** Status */
            status: string;
        };
        /**
         * HospitalResponse
         * @description Response schema for hospital
         */
        HospitalResponse: {
            /**
             * Name
             * @description Name of the hospital
             */
            name: string;
            /**
             * Address
             * @description Address of the veterinary hospital
             */
            address: string;
            /**
             * Phone Number
             * @description Contact phone number
             */
            phone_number: string;
            /**
             * Services
             * @description List of services offered (e.g., Surgery, X-Ray)
             */
            services?: string[];
            /**
             * Capacity
             * @description Maximum number of pet patients the hospital can admit
             * @default 0
             */
            capacity: number;
            /**
             * Is Active
             * @description Indicates if the hospital is active
             * @default true
             */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at?: string;
            /** Id */
            id?: components["schemas"]["PydanticObjectId"] | string | null;
        };
        /** Message */
        Message: {
            /** Detail */
            detail: string;
        };
        /** Page[HospitalResponse] */
        Page_HospitalResponse_: {
            /** Items */
            items: components["schemas"]["HospitalResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[PetResponse] */
        Page_PetResponse_: {
            /** Items */
            items: components["schemas"]["PetResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[UserResponse] */
        Page_UserResponse_: {
            /** Items */
            items: components["schemas"]["UserResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /**
         * PetResponse
         * @description Response schema for pet
         */
        PetResponse: {
            /**
             * Name
             * @description Name of the pet
             */
            name: string;
            /**
             * Description
             * @description Description of the pet
             */
            description?: string | null;
            /** @description GridFS ID of the pet image */
            image_id?: components["schemas"]["PydanticObjectId"] | null;
            /**
             * Is Active
             * @description Indicates if the pet is active
             * @default true
             */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at?: string;
            /** Id */
            id?: components["schemas"]["PydanticObjectId"] | string | null;
            /** @description ID of the owner of the pet */
            owner_id?: components["schemas"]["PydanticObjectId"];
            /**
             * Owner Name
             * @description Name of the owner
             */
            owner_name?: string | null;
            /**
             * Owner Username
             * @description Username of the owner
             */
            owner_username?: string | null;
        };
        /** @example 5eb7cf5a86d9755df3a6c593 */
        PydanticObjectId: string;
        /** SignIn */
        SignIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** @default jwt */
            strategy: components["schemas"]["Strategy"];
        };
        /**
         * Strategy
         * @enum {string}
         */
        Strategy: "cookies" | "jwt";
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token?: string | null;
            /** Token Type */
            token_type: string;
            /** Expires In */
            expires_in: number;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Scope */
            scope: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
        };
        /**
         * UpdateHospital
         * @description Schema for updating hospital data - all fields optional
         */
        UpdateHospital: {
            /**
             * Name
             * @description Name of the hospital
             */
            name?: string | null;
            /**
             * Address
             * @description Address of the veterinary hospital
             */
            address?: string | null;
            /**
             * Phone Number
             * @description Contact phone number
             */
            phone_number?: string | null;
            /**
             * Services
             * @description List of services offered
             */
            services?: string[] | null;
            /**
             * Capacity
             * @description Maximum number of pet patients the hospital can admit
             */
            capacity?: number | null;
            /**
             * Is Active
             * @description Indicates if the hospital is active
             */
            is_active?: boolean | null;
        };
        /**
         * UpdatePet
         * @description Schema for updating pet data - all fields optional
         */
        UpdatePet: {
            /**
             * Name
             * @description Name of the pet
             */
            name?: string | null;
            /**
             * Description
             * @description Description of the pet
             */
            description?: string | null;
            /**
             * Is Active
             * @description Indicates if the pet is active
             */
            is_active?: boolean | null;
            /** @description ID of the owner (User) to update */
            owner_id?: components["schemas"]["PydanticObjectId"] | null;
        };
        /**
         * UpdateUser
         * @description Schema for updating user data - all fields optional
         */
        UpdateUser: {
            /**
             * Username
             * @description Username of the user
             */
            username?: string | null;
            /**
             * Name
             * @description Name of the user
             */
            name?: string | null;
            /**
             * Email
             * @description Email address of the user
             */
            email?: string | null;
            /** @description Role assigned to the user */
            role?: components["schemas"]["UserRole"] | null;
            /**
             * Is Active
             * @description Indicates if the user is active
             */
            is_active?: boolean | null;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Username
             * @description Username of the user
             */
            username: string;
            /**
             * Name
             * @description Name of the user
             */
            name: string;
            /**
             * Email
             * @description Email address of the user
             */
            email?: string | null;
            /**
             * @description List of roles assigned to the user
             * @default user
             */
            role: components["schemas"]["UserRole"];
            /**
             * Is Active
             * @description Indicates if the user is active
             * @default true
             */
            is_active: boolean;
            /**
             * Last Login Date
             * @description Last login date of the user
             */
            last_login_date?: string | null;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at?: string;
            /** Id */
            id?: components["schemas"]["PydanticObjectId"] | string | null;
        };
        /**
         * UserRole
         * @description Enumeration for user roles
         * @enum {string}
         */
        UserRole: "user" | "admin" | "moderator";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_for_access_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_v1_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAccessTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    refresh_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAccessTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckResponse"];
                };
            };
        };
    };
    get_hospital_list: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_HospitalResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_hospital: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHospital"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HospitalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_hospitals_by_service: {
        parameters: {
            query: {
                service: string;
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_HospitalResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hospital: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HospitalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_hospital: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_hospital: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateHospital"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HospitalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pet_list: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PetResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePet"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_pet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pet_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_pet_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_pet_image_v1_pets__entity_id__image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pet_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_users: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
                search?: string | null;
                role?: components["schemas"]["UserRole"] | null;
                is_active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUser"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUser"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
